# Generated by Django 3.2.6 on 2022-11-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id_author', models.AutoField(primary_key=True, serialize=False)),
                ('name_author', models.CharField(default='unknown', max_length=35)),
                ('age_author', models.IntegerField(max_length=2)),
                ('mobile_number', models.IntegerField(max_length=10)),
                ('email_author', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Author1',
            fields=[
                ('id_author', models.AutoField(primary_key=True, serialize=False)),
                ('name_author', models.CharField(default='unknown', max_length=35)),
                ('age_author', models.IntegerField(max_length=2)),
                ('mobile_number', models.IntegerField(max_length=10)),
                ('email_author', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'name',
            },
        ),
    ]
