# Generated by Django 3.2.6 on 2022-11-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalnotes', '0002_auto_20221111_0910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={},
        ),
        migrations.RenameField(
            model_name='note',
            old_name='note_author',
            new_name='note_author_id',
        ),
        migrations.AddField(
            model_name='note',
            name='note_author_name',
            field=models.CharField(default='', max_length=35),
            preserve_default=False,
        ),
    ]
