# Generated by Django 3.2.6 on 2022-11-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalnotes', '0004_auto_20221111_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_author_name',
            field=models.CharField(default='unknown', max_length=35),
        ),
    ]
