# Generated by Django 3.2.6 on 2022-11-11 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalnotes', '0005_alter_note_note_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_author_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='personalnotes.author'),
            preserve_default=False,
        ),
    ]
